# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow at 16:00 UTC every day
  schedule:
  - cron: "0 16 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-10.15

    # retrieve secrets from github
    env:
        token: ${{ secrets.TOKEN}}
        apikey: ${{ secrets.APIKEY}}
        apisecretkey: ${{ secrets.APISECRETKEY}}
        access_token: ${{ secrets.ACCESS_TOKEN}}
        access_token_secret: ${{ secrets.ACCESS_TOKEN_SECRET}}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install ImageOptim-CLI
      - name: ImageOptim-CLI
        run: brew install imageoptim-cli

      # Setup R
      - name: Setup R
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: '4.0.3' # The R version to download (if necessary) and use.

      # Install all necesserary packages
      - name: Intall packages
        run: Rscript -e 'install.packages(c("stars", "tidyverse", "glue", "lubridate", "metR", "rtweet", "magick"))'

      # execute the script
      - name: Run script
        run: Rscript 02-eoliff.R
